title: Hannah's Homepage
description: A website with a blog
footer_text: Copyright 2021 Hannah Rothwell
header_feature_image: ../uploads/gabor-juhasz-b1zyw7sdm5w-unsplash.jpg
header_text: "From My Perspective "
header_text_color: "#ffffff"
bannerheight: 50vmax
logo: ../uploads/14411366.png
favicon: ../uploads/flower-3197493_1280.webp
gridlayout: true
fixednavbar: false
upzoom: true
