title: Hannah's Homepage
description: A website with a blog
footer_text: Copyright 2021 Hannah Rothwell
header_feature_image: ../uploads/richard-jacobs-8oenpcxktqq-unsplash.jpg
header_text: From My Perspective
header_text_color: "#ffffff"
bannerheight: 40vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
