title: Hannah's Homepage
description: A website with a blog
footer_text: Copyright 2021 Hannah Rothwell
header_feature_image: ../uploads/richard-jacobs-8oenpcxktqq-unsplash.jpg
header_text: From My Perspective
header_text_color: "#ffffff"
bannerheight: 40vmax
logo: ../uploads/screenshot-2021-02-01-at-09.03.01.png
favicon: ../uploads/rose-ico-flower-icon-png-favpng-1teks693klm62kqxnb0pperfr.jpg
gridlayout: false
fixednavbar: false
upzoom: true
